{{- $relname := .Release.Name -}}
{{- if eq .Values.routingMechanism "externalNames" }}
{{- range $index, $externalName := .Values.externalNames }}
kind: Service
apiVersion: v1
metadata:
  name: {{ $externalName.name }}
  namespace: {{ $relname }}
spec:
  type: ExternalName
  externalName: {{ $externalName.dns }}
---
{{- end }}
{{- end }}