tableName: SQLUser.rpybb
icqHost: k8s-5de22c52-a41557e8-6741242413-050efd481d2cf2fb.elb.us-east-1.amazonaws.com
jdbcConnectionString: jdbc:IRIS://127.0.0.1:1972/USER
image:
  registry: isc-rsingh.github.io/sds-charts
  repository: rsingh-python-icqbox

cloudProvider: "dev"
cloudProviderRegion: "dev-region"
compute:
  main:
    nodeTypeSelector: ""
    cpu: 100m
    memory: 512Mi

skaffold: 
  enabled: false
  image: to_be_defined_by_skaffold

# These are the secret fields needed to successfully deploy.
# They will be injected by the control plane:
# requiredSecrets:
#   intersystemsContainerRegistrySecret: ""

irisUserName: ""
irisPassword: "" 

