{{- $relname := .Release.Name -}}
kind: Service
apiVersion: v1
metadata:
  name: icq-{{ .Values.icqDeploymentId }}
  namespace: {{ $relname }}
spec:
  type: ExternalName
  externalName: {{ .Values.icqHostName }}

